/**
 * Still v2 — Comprehensive Master Wisdom Library
 * Hundreds of timeless quotes on Neuroscience, Stoicism, Zen, Breathwork & Deep Presence
 */

export const CALM_QUOTES = [
  // --- Neuroscience, Biology & Auditory Science ---
  { text: "Calm is a superpower. In a world of constant overreaction, stillness is your edge.", author: "Naval Ravikant" },
  { text: "A calm nervous system is the biological prerequisite for high-level creative problem solving.", author: "Neuroscience Principle" },
  { text: "When you slow your breathing to 6 breaths a minute, your brain signals the heart that you are completely safe.", author: "Heart Rate Variability Research" },
  { text: "Deep acoustic frequencies downregulate cortisol and activate somatic parasympathetic recovery.", author: "Acoustic Biology" },
  { text: "Alpha brainwaves (8–12 Hz) bridge conscious focus with effortless calm and heightened intuition.", author: "Cognitive Neuroscience" },
  { text: "Brownian noise filters ambient interruptions, protecting the fragile flow state of the prefrontal cortex.", author: "Auditory Masking Science" },
  { text: "Binaural delta waves stimulate the release of restorative somatic hormones and deep physical healing.", author: "Sleep Science" },
  { text: "The vagus nerve is the biological brake on stress; long exhalations activate it within seconds.", author: "Physiology Research" },
  { text: "Silence is not the absence of sound, but the presence of neural coherence and mental space.", author: "Neuro-Acoustics" },
  { text: "Rest is not idleness, but the essential neurobiological phase where memories consolidate and insights emerge.", author: "Cognitive Science" },
  { text: "Theta waves (4–7 Hz) occur during deep meditation and REM sleep, enabling spontaneous creative synthesis.", author: "Brainwave Research" },
  { text: "A quiet room is the ultimate luxury in a world engineered for digital hyper-stimulation.", author: "Stillness Philosophy" },
  { text: "The brain cannot enter deep creative focus while locked in sympathetic fight-or-flight reactivity.", author: "Neuro-Cognitive Study" },
  { text: "Isochronic pulses synchronize both cerebral hemispheres, fostering unified mental clarity.", author: "Acoustic Neurometry" },
  { text: "True mental recovery occurs when visual and auditory input is reduced to soothing, coherent rhythms.", author: "Sensory Biology" },

  // --- Stoicism & Ancient Classical Wisdom ---
  { text: "You have power over your mind, not outside events. Realize this, and you will find immense strength.", author: "Marcus Aurelius" },
  { text: "Tranquility is nothing else than the good ordering of the mind.", author: "Marcus Aurelius" },
  { text: "Nowhere can man find a quieter or more untroubled retreat than in his own soul.", author: "Marcus Aurelius" },
  { text: "Give your mind the same quiet dignity you give your body when you rest.", author: "Seneca" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca" },
  { text: "He who is calm and tranquil will hardly feel the pressure of age.", author: "Plato" },
  { text: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.", author: "Epictetus" },
  { text: "Silence is better than unmeaning words.", author: "Pythagoras" },
  { text: "Do not let future events disturb you. You will face them with the same weapon of reason.", author: "Marcus Aurelius" },
  { text: "He who fears death will never do anything worthy of a living man.", author: "Seneca" },
  { text: "A man is as wretched as he has convinced himself he is.", author: "Seneca" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
  { text: "How much more grievous are the consequences of anger than the causes of it.", author: "Marcus Aurelius" },
  { text: "No person has the power to have everything they want, but it is in their power not to want what they have not.", author: "Seneca" },

  // --- Zen, Taoism & Eastern Mindfulness ---
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },
  { text: "To a mind that is still, the whole universe surrenders.", author: "Zhuangzi" },
  { text: "Muddy water is best cleared by leaving it alone.", author: "Alan Watts" },
  { text: "Smile, breathe, and go slowly.", author: "Thich Nhat Hanh" },
  { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh" },
  { text: "Doing nothing is better than being busy doing nothing.", author: "Lao Tzu" },
  { text: "The quieter you become, the more you can hear.", author: "Ram Dass" },
  { text: "In the midst of movement and chaos, keep stillness inside of you.", author: "Deepak Chopra" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "When you realize nothing is lacking, the whole world belongs to you.", author: "Lao Tzu" },
  { text: "In silence there is eloquence. Stop turning the wheel of thinking.", author: "Rumi" },
  { text: "The soul always knows what to do to heal itself. The challenge is to silence the mind.", author: "Caroline Myss" },
  { text: "Step out of the circle of time and into the circle of love and stillness.", author: "Rumi" },
  { text: "To be calm is the highest achievement of the self.", author: "Zen Wisdom" },
  { text: "Within you, there is a stillness and a sanctuary to which you can retreat at any time.", author: "Hermann Hesse" },
  { text: "Do not let the behavior of others destroy your inner peace.", author: "Dalai Lama" },
  { text: "The mind is like water. When it's turbulent, it's difficult to see. When it's calm, everything becomes clear.", author: "Prasad Mahes" },
  { text: "Tension is who you think you should be. Relaxation is who you are.", author: "Chinese Proverb" },
  { text: "Learn to be quiet enough to hear the genuine within yourself so that you can hear it in others.", author: "Marian Wright Edelman" },
  { text: "He who knows when he has enough is rich.", author: "Lao Tzu" },
  { text: "True intelligence requires a tranquil observer behind the thoughts.", author: "Jiddu Krishnamurti" },
  { text: "One of the best feelings in the world is knowing your presence and absence both mean something.", author: "Zen Maxim" },
  { text: "Look at a tree, a flower, a plant. Let your awareness rest upon it. How still they are, how deeply rooted in Being.", author: "Eckhart Tolle" },
  { text: "The primary cause of unhappiness is never the situation but your thoughts about it.", author: "Eckhart Tolle" },
  { text: "Inner peace begins the moment you choose not to allow another person or event to control your emotions.", author: "Pema Chödrön" },
  { text: "You cannot see your reflection in boiling water. Similarly, you cannot see the truth in a state of anger.", author: "Ancient Proverb" },
  { text: "Be like water making its way through cracks. Adjust to the object, and you shall find a way around or through it.", author: "Bruce Lee" },
  { text: "Empty your mind, be formless, shapeless, like water.", author: "Bruce Lee" },
  { text: "Wherever you are, be there totally.", author: "Eckhart Tolle" },
  { text: "Your goal is not to battle with the mind, but to witness the mind.", author: "Swami Muktananda" },

  // --- Deep Work, Modern Presence & Philosophy ---
  { text: "Stillness is where all creative insights and profound breakthroughs are born.", author: "Rick Rubin" },
  { text: "Clarity of mind requires space, not speed.", author: "James Clear" },
  { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
  { text: "Slow down and everything you are chasing will come around and catch you.", author: "John De Paola" },
  { text: "Your mind will answer most questions if you learn to relax and wait for the answer.", author: "William S. Burroughs" },
  { text: "Calmness is the cradle of power.", author: "Josiah Gilbert Holland" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Don't underestimate the value of Doing Nothing, of just going along, listening to all the things you can't hear.", author: "A.A. Milne" },
  { text: "The ability to perform deep work is becoming increasingly rare at exactly the same time it is becoming increasingly valuable.", author: "Cal Newport" },
  { text: "Who you are, what you think, feel, and do, is the sum of what you focus on.", author: "Winifred Gallagher" },
  { text: "Busyness is a form of laziness — lazy thinking and indiscriminate action.", author: "Tim Ferriss" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "The less you open your heart to others, the more your heart suffers.", author: "Deepak Chopra" },
  { text: "Nothing diminishes anxiety faster than action, and nothing deepens insight faster than stillness.", author: "Naval Ravikant" },
  { text: "Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.", author: "Wayne Dyer" },
  { text: "There are two ways to get enough. One is to continue to accumulate more. The other is to desire less.", author: "G.K. Chesterton" },
  { text: "It is not daily increase, but daily decrease. Hack away at the unessential.", author: "Bruce Lee" },
  { text: "The greatest art is the art of letting go.", author: "Mingyur Rinpoche" },
  { text: "Deep breathing is our body's built-in reset button.", author: "Somatic Health Research" },
  { text: "Solitude is where I place my chaos to rest and awaken my inner stillness.", author: "Kac Young" },
  { text: "Silence is the sleep that nourishes wisdom.", author: "Francis Bacon" },
  { text: "When you focus on the present moment, fear and regret lose their power.", author: "Mindfulness Principle" },
  { text: "A quiet mind can hear the whisper of intuition over the shout of anxiety.", author: "Stillness Maxim" },
  { text: "Let your breath be your anchor whenever the waves of thought become turbulent.", author: "Zen Teacher" },
  { text: "Every profound realization began in a moment of quiet listening.", author: "Ethereal Wisdom" },
  { text: "Nothing is as calming as the realization that you do not need to react to everything you feel.", author: "Emotional Resilience" },
  { text: "Hold your center. The world will always swirl around you, but you decide what enters your sanctuary.", author: "Daily Stillness" },
  { text: "Make room for silence, and clarity will naturally fill the void.", author: "Deep Presence" }
];
