/**
 * Still v2 — Curated Wisdom on Calmness, Neuroscience & Stillness
 * 100+ timeless quotes from neuroscience, philosophy, mindfulness, and deep work
 */

export const CALM_QUOTES = [
  { text: "Calm is a superpower. In a world of constant overreaction, stillness is your edge.", author: "Naval Ravikant" },
  { text: "A calm nervous system is the biological prerequisite for high-level creative problem solving.", author: "Neuroscience Principle" },
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The quieter you become, the more you can hear.", author: "Ram Dass" },
  { text: "When you slow your breathing to 6 breaths a minute, your brain signals the heart that you are safe.", author: "Heart Rate Variability Research" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },
  { text: "Stillness is where all creative insights and profound breakthroughs are born.", author: "Rick Rubin" },
  { text: "Clarity of mind requires space, not speed.", author: "James Clear" },
  { text: "Smile, breathe, and go slowly.", author: "Thich Nhat Hanh" },
  { text: "In the midst of movement and chaos, keep stillness inside of you.", author: "Deepak Chopra" },
  { text: "The soul always knows what to do to heal itself. The challenge is to silence the mind.", author: "Caroline Myss" },
  { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Within you, there is a stillness and a sanctuary to which you can retreat at any time.", author: "Hermann Hesse" },
  { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh" },
  { text: "To a mind that is still, the whole universe surrenders.", author: "Zhuangzi" },
  { text: "The primary cause of unhappiness is never the situation but your thoughts about it.", author: "Eckhart Tolle" },
  { text: "He who is calm and tranquil will hardly feel the pressure of age.", author: "Plato" },
  { text: "Deep acoustic frequencies downregulate cortisol and activate somatic recovery.", author: "Acoustic Biology" },
  { text: "There is nothing more restorative than sitting in a quiet room and letting the world spin on without you.", author: "Stillness Philosophy" },
  { text: "Tension is who you think you should be. Relaxation is who you are.", author: "Chinese Proverb" },
  { text: "Learn to be quiet enough to hear the genuine within yourself so that you can hear it in others.", author: "Marian Wright Edelman" },
  { text: "Muddy water is best cleared by leaving it alone.", author: "Alan Watts" },
  { text: "Your mind will answer most questions if you learn to relax and wait for the answer.", author: "William S. Burroughs" },
  { text: "Calmness is the cradle of power.", author: "Josiah Gilbert Holland" },
  { text: "Doing nothing is better than being busy doing nothing.", author: "Lao Tzu" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
  { text: "Slow down and everything you are chasing will come around and catch you.", author: "John De Paola" },
  { text: "Breathe in peace, breathe out noise.", author: "Mindfulness Core" },
  { text: "Alpha brainwaves (8–12 Hz) bridge conscious focus with effortless calm.", author: "Cognitive Neuroscience" },
  { text: "The greatest mistake you can make in life is to be continually fearing you will make one.", author: "Elbert Hubbard" },
  { text: "Give your mind the same quiet dignity you give your body when you rest.", author: "Seneca" },
  { text: "Rest is not idleness, and to lie sometimes on the grass is by no means a waste of time.", author: "John Lubbock" },
  { text: "He who knows when he has enough is rich.", author: "Lao Tzu" },
  { text: "In silence there is eloquence. Stop turning the wheel of thinking.", author: "Rumi" },
  { text: "True intelligence requires a tranquil observer behind the thoughts.", author: "Jiddu Krishnamurti" },
  { text: "One of the best feelings in the world is knowing your presence and absence both mean something.", author: "Zen Maxim" },
  { text: "Brownian noise filters ambient interruptions, protecting the flow state.", author: "Auditory Masking Science" },
  { text: "Do not let the behavior of others destroy your inner peace.", author: "Dalai Lama" },
  { text: "To be calm is the highest achievement of the self.", author: "Zen Wisdom" },
  { text: "Step out of the circle of time and into the circle of love and stillness.", author: "Rumi" },
  { text: "When you realize nothing is lacking, the whole world belongs to you.", author: "Lao Tzu" },
  { text: "The mind is like water. When it's turbulent, it's difficult to see. When it's calm, everything becomes clear.", author: "Prasad Mahes" },
  { text: "Don't underestimate the value of Doing Nothing, of just going along, listening to all the things you can't hear.", author: "Winnie the Pooh" },
  { text: "Tranquility is nothing else than the good ordering of the mind.", author: "Marcus Aurelius" },
  { text: "Binaural delta waves trigger the release of human growth hormone and deep physical restoration.", author: "Sleep Science" },
  { text: "The best remedy for those who are afraid, lonely or unhappy is to go outside, somewhere where they can be quiet.", author: "Anne Frank" },
  { text: "Inner peace begins the moment you choose not to allow another person or event to control your emotions.", author: "Pema Chödrön" },
  { text: "Look at a tree, a flower, a plant. Let your awareness rest upon it. How still they are, how deeply rooted in Being.", author: "Eckhart Tolle" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" }
];
